apiVersion: v1
kind: Secret
metadata:
  name: webhook-secret
stringData:
  #https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line#creating-a-token
  token: a0c0a55da920ad02715ee8b1026fe548f3bacf5e
  secret: random-string-data
