apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airlineprediction-sa-admin-dev
  namespace: airlineprediction-stream-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: airlineprediction-sa
  namespace: airlineprediction-stream-build
