kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: airline-predictions-generator
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  namespace: builds-tutorial
  labels:
    app: airline-predictions-generator
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - airline-predictions-generator
        from:
          kind: ImageStreamTag
          namespace: builds-tutorial
          name: 'airline-predictions-generator:latest'
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: airline-predictions-generator
    deploymentconfig: airline-predictions-generator
  template:
    metadata:
      labels:
        app: airline-predictions-generator
        deploymentconfig: airline-predictions-generator
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: airline-predictions-generator
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
