kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: python-lyapp
  namespace: builds-tutorial
  generation: 1
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      #annotations: null
      from:
        kind: DockerImage
        name: 'docker.io/ably77/python-lyapp:latest'
      generation: 1
      importPolicy:
        scheduled: true
        insecure: true
      referencePolicy:
        type: Source
