apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-testbed-argo-grafana-azure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dr
  source:
    repoURL: https://github.com/ably77/openshift-testbed-argo-grafana
    targetRevision: HEAD
    path: .
  destination:
    server: https://api.ly-demo-ly-ocpazure.com:6443
    namespace: myproject
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
