kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  name: python-ly-app
  #generateName: python-lyapp-
  namespace: builds-tutorial
  labels:
    app: python-lyapp
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - python-lyapp
        from:
          kind: ImageStreamTag
          namespace: builds-tutorial
          name: 'python-lyapp:latest'
        lastTriggeredImage: >-
          docker.io/ably77/python-lyapp@sha256:34224adb5c500a0843ccfbeeb407a1c731418e4352ca0f6cc95eb8d70004ced1
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: python-lyapp
    deploymentconfig: python-lyapp
  template:
    metadata:
      labels:
        app: python-lyapp
        deploymentconfig: python-lyapp
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: python-lyapp
          image: >-
            docker.io/ably77/python-lyapp@sha256:34224adb5c500a0843ccfbeeb407a1c731418e4352ca0f6cc95eb8d70004ced1
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
