kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: blog-django-py
  namespace: builds-tutorial
  labels:
    app: blog-django-py
    app.kubernetes.io/component: blog-django-py
    app.kubernetes.io/instance: blog-django-py
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'blog-django-py:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    # option to replace Dockerfile FROM image with ImageStreamTag image
    #dockerStrategy:
    #  from:
    #    kind: ImageStreamTag
    #    name: 'python:latest'
    #    namespace: openshift
    # option to replace Dockerfile FROM image with another specified image
    #dockerStrategy:
    #  from:
    #    kind: DockerImage
    #    name: 'centos/python-35-centos7:latest'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift-katacoda/blog-django-py'
  triggers:
    - type: GitHub
      github:
        secret: H5yQIfcBCx8VngIGRFWF
    - type: Generic
      generic:
        secret: diHWHFwkdgFnKARLPuc3
    - type: ConfigChange
    - type: ImageChange
  runPolicy: Serial
