kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: blog-django-py
  namespace: builds-tutorial
  labels:
    app: blog-django-py
    app.kubernetes.io/component: blog-django-py
    app.kubernetes.io/instance: blog-django-py
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        #name: 'python:latest'
        name: 'python:3.5'
        #name: 'python:3.6'
      incremental: true
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift-katacoda/blog-django-py'
  triggers:
    - type: GitHub
      github:
        secret: H5yQIfcBCx8VngIGRFWF
    - type: Generic
      generic:
        secret: diHWHFwkdgFnKARLPuc3
    - type: ConfigChange
    - type: ImageChange
  runPolicy: Serial
  output:
    to:
      kind: ImageStreamTag
      name: 'blog-django-py:latest'
