kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: ruby-s2i
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  namespace: snow
  labels:
    app: ruby-s2i
    buildtype: s2i
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - ruby-s2i
        from:
          kind: ImageStreamTag
          namespace: snow
          name: 'ruby-s2i:latest'
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: ruby-s2i
    deploymentconfig: ruby-s2i
  template:
    metadata:
      labels:
        app: ruby-s2i
        deploymentconfig: ruby-s2i
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: ruby-s2i
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
