kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: blog-django-py
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  namespace: snow
  labels:
    app: blog-django-py
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - blog-django-py
        from:
          kind: ImageStreamTag
          namespace: snow
          name: 'blog-django-py:latest'
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: blog-django-py
    deploymentconfig: blog-django-py
  template:
    metadata:
      labels:
        app: blog-django-py
        deploymentconfig: blog-django-py
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: blog-django-py
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
