apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: oc-client
  namespace: default
  labels:
    name: oc-client
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  source:
    type: Git
    git:
      uri: 'https://github.com/ably77/oc-client.git'
  strategy:
    type: Docker
    #dockerStrategy:
    #  from:
    #    kind: ImageStreamTag
    #    name: 'ruby:2.5'
    #    namespace: openshift
    #  env:
    #    - name: EXAMPLE
    #      value: sample-app
  output:
    to:
      kind: ImageStreamTag
      name: 'oc-client:latest'
