kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: oc-client
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  namespace: default
  labels:
    app: oc-client
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - oc-client
        from:
          kind: ImageStreamTag
          namespace: default
          name: 'oc-client:latest'
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: oc-client
    deploymentconfig: oc-client
  template:
    metadata:
      labels:
        app: oc-client
        deploymentconfig: oc-client
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: oc-client
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
          command:
          - /bin/bash
          - -x
          - -c
          - |           
            git clone https://github.com/ably77/openshift-testbed.git
            cd openshift-testbed
            ./scripts/runme.sh
            oc delete dc/oc-client -n default
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
