apiVersion: v1
kind: Secret
metadata:
  name: webhook-secret
stringData:
  #https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line#creating-a-token
  #token: <insert github personal access token here>
  token: 15618528b0a20389dad95a53450e54ccecf4c635
  secret: random-string-data
